SELECT 	*
FROM	DEPARTMENTS ; 

SELECT *
FROM	COUNTRIES ; 

CREATE TABLE USER_TBL(
	ID 		VARCHAR2(50) PRIMARY KEY , 
	PWD		VARCHAR2(50) NOT NULL , 
	NAME    VARCHAR2(50) NOT NULL , 
	POINT   NUMBER       DEFAULT 1000
);

SELECT 	*
FROM	USER_TBL ;

INSERT INTO USER_TBL
VALUES('jslim','jslim','임정섭',1000);

/*SELECT 	*
FROM	USER_TBL 
WHERE	ID = ? AND PWD = ? ; 

INSERT INTO USER_TBL
VALUES (?,?,?,?) ;

UPDATE 	USER_TBL 
SET		POINT = ?  
WHERE	ID = ? ; 

DELETE 	FROM USER_TBL
WHERE	ID = ? ; 
*/
drop table BBS_TBL;
CREATE TABLE BBS_TBL(
	SEQ NUMBER PRIMARY KEY,
	SUBJECT VARCHAR2(50),
	CONTENT VARCHAR2(1000),
	WRITER VARCHAR2(50),
	REGDATE DATE,
	VIEWCNT NUMBER
);


create SEQUENCE BBS_SEQ;

INSERT INTO BBS_TBL
VALUES(BBS_SEQ.NEXTVAL,'공지','냉무','JSLIM',sysdate,0);

INSERT INTO BBS_TBL
VALUES(BBS_SEQ.NEXTVAL,'삭제','delete','M',sysdate,0);


select * from BBS_TBL;


/*
 * dynamic query
 * FILTER CONDITION - SUBJECT OR WRITTER
 * KEYWORD			- 사용자의 입력
 * */


SELECT * FROM BBS_TBL WHERE SUBJECT LIKE '%휴강%';


SELECT * FROM BBS_TBL WHERE SUBJECT='수정함';

SELECT SEQ, SUBJECT, CONTENT, WRITER, REGDATE, VIEWCNT
			FROM BBS_TBL
			ORDER BY SEQ DESC
